version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: jakarta.annotation:jakarta.annotation-api
        versions: "[2.0,)"
      - dependency-name: org.apache.tomcat:tomcat-catalina
        versions: "[10.1,)"
